name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23li4BVeEbwyHC236e"
GITHUB_OWNER = "longge83"
GITHUB_REPO = "navsphere-demo"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://a1fa8ef0.navsphere-dn1.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://a1fa8ef0.navsphere-dn1.pages.dev"

